### ISSUE TITLE
Errors in dataset notebooks

### ISSUE THREAD

**Issue by alonjacovi** [successar/FRESH#3]
Hi, I got various errors in the data preparation notebooks for "evinf", "SST", "movies" and "multirc"

SST error:
```bash
~/FRESH/Datasets/SST/Process.ipynb in <module>
      6 for key in ['train', 'dev', 'test'] :
      7     data_key = data[data.exp_split == key].to_dict(orient='records')
----> 8     data_key = [{'document' : clean_text(x['text']), 'label' : x['label']} for x in tqdm(data_key)]
      9     f = open('data/' + key + '.jsonl', 'w')
     10     f.write('\n'.join([json.dumps(line) for line in data_key]))

~/FRESH/Datasets/SST/Process.ipynb in <listcomp>(.0)
      6 for key in ['train', 'dev', 'test'] :
      7     data_key = data[data.exp_split == key].to_dict(orient='records')
----> 8     data_key = [{'document' : clean_text(x['text']), 'label' : x['label']} for x in tqdm(data_key)]
      9     f = open('data/' + key + '.jsonl', 'w')
     10     f.write('\n'.join([json.dumps(line) for line in data_key]))

NameError: name 'clean_text' is not defined
```

evinf:
`ModuleNotFoundError: No module named 'preprocessor'`
(pip install preprocessor resulted in a different AttributeError for the attribute "read_prompts", so I assume it's not that module?)

movies/multirc:
`ModuleNotFoundError: No module named 'rationale_benchmark'`
Solved by git cloning the ERASER repo into the project (since I don't think it's available by pip?)

There were some other import errors in various places that I didn't keep track of, solved by pip installing them as they happened

**Comment by successar** [comment]
Hi Alon,

Thanks for pointing this out. I am still in process of cleaning up few of these issues. They should be done by end of week.

**Comment by successar** [comment]
Datasets code Updated. Please feel free to reopen the issue if you still face problem to load the datasets.
